package com.sampson.shoplist.model

import com.sampson.shoplist.R

object PopulateModel {

    fun populateCategory() : ArrayList<Category>{
        val categories = arrayListOf<Category>()
        categories.add(Category(1,"Açougue"))
        categories.add(Category(2,"Bebidas"))
        categories.add(Category(3,"Biscoitos"))
        categories.add(Category(4,"Cereais"))
        categories.add(Category(5,"Congelados"))
        categories.add(Category(6,"Enlatados"))
        categories.add(Category(7,"Farináceos"))
        categories.add(Category(8,"Higiene"))
        categories.add(Category(9,"Hortifruti"))
        categories.add(Category(10,"Laticínios"))
        categories.add(Category(11,"Limpeza"))
        categories.add(Category(12,"Massas"))
        categories.add(Category(13,"Matinais"))
        categories.add(Category(14,"Óleos"))
        categories.add(Category(15,"Padaria"))
        categories.add(Category(16,"Peixaria"))
        categories.add(Category(17,"Salgados"))
        categories.add(Category(18,"Temperos"))
        categories.add(Category(19,"Utilidades"))
        categories.add(Category(20,"Outros"))
        return categories
    }

    fun populateItem() : ArrayList<Item> {
        val items = arrayListOf<Item>()
        items.add(Item(1,"Abóbora",9))
        items.add(Item(2,"Abobrinha",9))
        items.add(Item(3,"Absorvente",8))
        items.add(Item(4,"Açúcar",18))
        items.add(Item(5,"Água Sanitária",11))
        items.add(Item(6,"Álcool",11))
        items.add(Item(7,"Alho",9))
        items.add(Item(8,"Almôndega",5))
        items.add(Item(9,"Amaciante",11))
        items.add(Item(10,"Arroz",4))
        items.add(Item(11,"Azeite",14))
        items.add(Item(12,"Banana",9))
        items.add(Item(13,"Batata",9))
        items.add(Item(14,"Berinjela",9))
        items.add(Item(15,"Beterraba",9))
        items.add(Item(16,"Bisnaguinha",15))
        items.add(Item(17,"Bloco Higiênico",11))
        items.add(Item(18,"Bono",3))
        items.add(Item(19,"Café",13))
        items.add(Item(20,"Canela",18))
        items.add(Item(21,"Catchup",18))
        items.add(Item(22,"Cebola",9))
        items.add(Item(23,"Cenoura",9))
        items.add(Item(24,"Cera Ardósia",11))
        items.add(Item(25,"Cera Taco",11))
        items.add(Item(26,"Chá",2))
        items.add(Item(27,"Chuchu",9))
        items.add(Item(28,"Condicionador",8))
        items.add(Item(29,"Creme Cracker",3))
        items.add(Item(30,"Creme de Leite",10))
        items.add(Item(31,"Danoninho",10))
        items.add(Item(32,"Desodorante",8))
        items.add(Item(33,"Detergente",11))
        items.add(Item(34,"Escova de Dente",8))
        items.add(Item(35,"Esponja",11))
        items.add(Item(36,"Farinha Mandioca",7))
        items.add(Item(37,"Farinha Trigo",7))
        items.add(Item(38,"Feijão",4))
        items.add(Item(39,"Fermento",7))
        items.add(Item(40,"Filtro Café",19))
        items.add(Item(41,"Frango",5))
        items.add(Item(42,"Gelatina",20))
        items.add(Item(43,"Geleia",13))
        items.add(Item(44,"Gilette",8))
        items.add(Item(45,"Goiabada",6))
        items.add(Item(46,"Goiabinha",3))
        items.add(Item(47,"Sabonete Líquido Granado",8))
        items.add(Item(48,"Guarana Natural",2))
        items.add(Item(49,"Guardanapo",11))
        items.add(Item(50,"Inhame",9))
        items.add(Item(51,"Inseticida",19))
        items.add(Item(52,"Iogurte",10))
        items.add(Item(53,"Lata de Ervilha",6))
        items.add(Item(54,"Lata de Milho",6))
        items.add(Item(55,"Leite Condensado",6))
        items.add(Item(56,"Leite em pó",10))
        items.add(Item(57,"Lingüiça",17))
        items.add(Item(58,"Maça",9))
        items.add(Item(59,"Macarrão",12))
        items.add(Item(60,"Maionese",18))
        items.add(Item(61,"Biscoito Maisena",3))
        items.add(Item(62,"Mamão",9))
        items.add(Item(63,"Manteiga",10))
        items.add(Item(64,"Mate em Pó",2))
        items.add(Item(65,"Mel",18))
        items.add(Item(66,"Mussarela",10))
        items.add(Item(67,"Nescafé",13))
        items.add(Item(68,"Nescau",13))
        items.add(Item(69,"Nuggets",5))
        items.add(Item(70,"Óleo Girassol",14))
        items.add(Item(71,"Orégano",18))
        items.add(Item(72,"Oreo",3))
        items.add(Item(73,"Ovos",9))
        items.add(Item(74,"Pano de chão",19))
        items.add(Item(75,"Pão Forma",15))
        items.add(Item(76,"Papel Higiênico",8))
        items.add(Item(77,"Papel Toalha",11))
        items.add(Item(78,"Pasta de Dente",8))
        items.add(Item(79,"Pepino",9))
        items.add(Item(80,"Perfex",11))
        items.add(Item(81,"Pimentão",9))
        items.add(Item(82,"Pipoca",4))
        items.add(Item(83,"Polvilho",3))
        items.add(Item(84,"Presunto",5))
        items.add(Item(85,"Queijo minas",10))
        items.add(Item(86,"Queijo ralado",10))
        items.add(Item(87,"Requeijão",10))
        items.add(Item(88,"Ricota",10))
        items.add(Item(89,"Rosquinha",3))
        items.add(Item(90,"Sabão em Pó",11))
        items.add(Item(91,"Sabonete",11))
        items.add(Item(92,"Saco de Lixo 10",19))
        items.add(Item(93,"Saco de Lixo 100",19))
        items.add(Item(94,"Saco de Lixo 15",19))
        items.add(Item(95,"Saco de Lixo 30",19))
        items.add(Item(96,"Sal",17))
        items.add(Item(97,"Salsicha",5))
        items.add(Item(98,"Sapólio",11))
        items.add(Item(99,"Shampoo",8))
        items.add(Item(100,"Suco Uva",2))
        items.add(Item(101,"Sucos Garrafa",2))
        items.add(Item(102,"Sucrilhos",13))
        items.add(Item(103,"Toddynho",10))
        items.add(Item(104,"Tomate",9))
        items.add(Item(105,"Trakinas",3))
        items.add(Item(106,"Vaquinha",3))
        items.add(Item(107,"Veja",11))
        items.add(Item(108,"Wafer",3))
        items.add(Item(109,"Ziploc",19))
        return items
    }

    fun populateMarket() : ArrayList<Market> {
        val markets = arrayListOf<Market>()
        markets.add(Market("Guanabara","https://www.supermercadosguanabara.com.br/encarte", R.drawable.guanabara))
        markets.add(Market("Mundial","https://www.supermercadosmundial.com.br/encarte", R.drawable.mundial))
        markets.add(Market("Prezunic","https://www.prezunic.com.br/ofertas/encartes/", R.drawable.prezunic))
        markets.add(Market("Rede Economia","https://www.redeconomia.com.br/ofertas/encarte/", R.drawable.redeconomia))
        markets.add(Market("Super Market","https://smpravc.com.br/encartes/", R.drawable.supermarket))
        markets.add(Market("Hortifruti","https://www.hortifruti.com.br/", R.drawable.hortifruti))
        markets.add(Market("SuperPrix","https://www.superprix.com.br/", R.drawable.superprix))
        markets.add(Market("Zona Sul","https://www.zonasul.com.br/", R.drawable.zonasul))
        markets.add(Market("Pão de Açucar","https://www.paodeacucar.com/", R.drawable.paodeacucar))
        markets.add(Market("Costazul","https://www.costazulsupermercados.com.br/encarte/", R.drawable.costazul))
        markets.add(Market("Assai","https://www.assai.com.br/ofertas/rio-de-janeiro/assai-tijuca/", R.drawable.assai))
        return markets
    }
}

